### ISSUE TITLE
Backport patch for newer GLinet Devices

### ISSUE THREAD

**Issue by MaStr** [FriedZombie/OpenWrt_Attitude-Adjustment_backports#6]
Hey,
do you think you can backport these patches including a new imagebuilder version?

https://dev.openwrt.org/changeset/47620

Supporting the new GLiNet devices would be very cool,

best regards
Matthias

**Comment by FriedZombie** [comment]
Added the wr1043ndv3 in a3b93df 676a860 14a07d1
and added the AR-150 in 58d5fb4
